city: Лабинск, Краснодарский край
driver_path: c:\chromedriver.exe
browser: chrome
token: 92ba0871-9202-42e9-b511-0f63f972d4d4
extra: true
lang: ru_RU
limit: 7
hours: true
mail_password: XJhDxzzNV5iVxqda32C2
fromaddr_report: ivan.zakharchenko.test@mail.ru
toaddr_report: zakharka2000@ya.ru